// auth.js
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_INITIALIZED = 'AUTH_INITIALIZED'
export const SET_USER = 'SET_USER'
export const UNAUTHENTICATED = 'UNAUTHENTICATED'

export const HOME_BANNERS_INIT = 'HOME_BANNERS_INIT'
export const HOME_BANNERS_LOADED = 'HOME_BANNERS_LOADED'

export const HOME_ARTICLES_INIT = 'HOME_ARTICLES_INIT'
export const HOME_ARTICLES_LOADED = 'HOME_ARTICLES_LOADED'

export const MESSAGES_LIST_INIT = 'MESSAGES_LIST_INIT'
export const MESSAGES_LIST_LOADED = 'MESSAGES_LIST_LOADED'

export const EVENTS_INIT = 'EVENTS_INIT'
export const EVENTS_LOADED = 'EVENTS_LOADED'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
