// auth.js
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_INITIALIZED = 'AUTH_INITIALIZED'
export const SET_USER = 'SET_USER'
export const UNAUTHENTICATED = 'UNAUTHENTICATED'

export const HOME_BANNERS_INIT = 'HOME_BANNERS_INIT'
export const HOME_BANNERS_LOADED = 'HOME_BANNERS_LOADED'

export const HOME_ARTICLES_INIT = 'HOME_ARTICLES_INIT'
export const HOME_ARTICLES_LOADED = 'HOME_ARTICLES_LOADED'

export const MESSAGES_LIST_INIT = 'MESSAGES_LIST_INIT'
export const MESSAGES_LIST_LOADED = 'MESSAGES_LIST_LOADED'

export const ARTICLES_DETAIL_INIT = 'ARTICLES_DETAIL_INIT'
export const ARTICLES_DETAIL_LOADED = 'ARTICLES_DETAIL_LOADED'

export const MESSAGES_DETAIL_INIT = 'MESSAGES_DETAIL_INIT'
export const MESSAGES_DETAIL_LOADED = 'MESSAGES_DETAIL_LOADED'

export const USERS_DETAIL_INIT = 'USERS_DETAIL_INIT'
export const USERS_DETAIL_LOADED = 'USERS_DETAIL_LOADED'
export const USERS_DETAIL_FAILED = 'USERS_DETAIL_FAILED'

export const EVENTS_INIT = 'EVENTS_INIT'
export const EVENTS_LOADED = 'EVENTS_LOADED'

export const THANKYOU_INIT = 'THANKYOU_INIT'
export const THANKYOU_LOADED = 'THANKYOU_LOADED'

export const FEEDBACK_LIST_INIT = 'FEEDBACK_LIST_INIT'
export const FEEDBACK_LIST_LOADED = 'FEEDBACK_LIST_LOADED'

export const CHECKINS_INIT = 'CHECKINS_INIT'
export const CHECKINS_LOADED = 'CHECKINS_LOADED'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
